app:
  version: SNAPSHOT
  build: local
info:
 app:
  name: sc
  description: sc
  version:  1
  build: 1
spring:
  datasource:
    url: jdbc:mysql://rm-uf6412jm3hb7ra8i4io.mysql.rds.aliyuncs.com/ecdb
    username: root
    password: Pass123@
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: shoppingCart
  profiles:
    include: build
    jackson:
    serialization:
      write-dates-as-timestamps: false
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSS'Z'
  jmx:
    enabled: true
    unique-names: true
    default-domain: com.exactuals.reconprocessor
  jpa:
    show-sql: true

security:
 require-ssl: true
server:
 port: 8443
 servlet:
  context-path: /shopping-cart
management:
 endpoint:
  health:
   enabled: true
  info:
   enabled: true
 health:
  time-to-live: 60000
  sensitive: false
  db:
   enabled: false
  redis:
   enabled: false
  diskspace:
   enabled: true
   threshold: 10485760
  status:
   order: DOWN, OUT_OF_SERVICE, UNKNOWN, UP
 endpoints:
  enabled-by-default: false
  web:
   base-path: /
   exposure:
    include:
    - health
    - info
    - metrics
   path-mapping:
    health: /health
